crypto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/predictions/')),
    path('admin/', admin.site.urls),
    path('market/', include('market.urls')),
    path('predictions/', include('predictions.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

predictions/urls.py
from django.urls import path
from . import views

app_name = 'predictions'
urlpatterns = [
    path('', views.index_view, name='index'),
    path('top/', views.top_predictions, name='top_predictions'),
    path('predictions/<slug:slug>/', views.prediction_view, name='prediction'),
    path('add_prediction/', views.add_prediction, name='add_prediction'),
]

predictions/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Prediction(models.Model):
    PREDICTION_TYPES = (
        ('L', 'Long'),
        ('S', 'Short'),
    )
    # user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    coin_name = models.SlugField(help_text='Short name of a coin')
    prediction_type = models.CharField(max_length=1, choices=PREDICTION_TYPES, null=True)
    description = models.CharField(max_length=500)
    pub_date = models.DateTimeField('date published')
    votes = models.IntegerField(default=0)
    entry = models.DecimalField(max_digits=10, default=0, decimal_places=8)
    stop_loss = models.DecimalField(max_digits=10, default=0, decimal_places=8)
    mcap_name = models.CharField(max_length=50, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default='1')

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ["-coin_name"]

    def get_absolute_url(self):
        """
        Returns the url to access a particular instance of the model.
        """
        return reverse('prediction', args=[str(self.id)])

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Target(models.Model):
    prediction = models.ForeignKey(Prediction, on_delete=models.CASCADE)
    TARGET_TYPES = (
        ('P', 'Pending'),
        ('R', 'Reached'),
        ('C', 'Closed'),
    )
    target_status = models.CharField(max_length=1, choices=TARGET_TYPES, default='P')
    prediction_target = models.DecimalField(max_digits=10, default=0, decimal_places=8)

    def __str__(self):
        return str(self.prediction_target)

    class Meta:
        ordering = ["prediction_target"]

predictions/forms.py
from django.forms import ModelForm
from django.db import models
from .models import Prediction

class CreatePrediction(ModelForm):
    class Meta:
        model = Prediction
        fields = '__all__'#['title', 'coin_name', 'prediction_type', 'description', 'entry', 'stop_loss', 'target']

       # prediction_target = models.DecimalField(max_digits=10, default=0, decimal_places=8)
        # prediction_target = models.DecimalField(max_digits=10, default=0, decimal_places=8)

predictions/views.py
from django.shortcuts import render
from django.views import generic
from django.shortcuts import render, get_object_or_404
import requests
from django.db.models import F
import json
from .forms import CreatePrediction

from .models import Prediction, Target


def index_view(request):
    all_predictions = Prediction.objects.order_by('-pub_date')
    return render(request, 'predictions/index.html',
                  {'all_predictions': all_predictions})


def prediction_view(request, slug):
    prediction = get_object_or_404(Prediction, coin_name=slug)
    target = prediction.target_set.all()
    coin_url = 'https://api.coinmarketcap.com/v1/ticker/%s' \
        % (prediction.mcap_name.lower())
    response = requests.get(coin_url)
    load_coin = json.loads(response.text)
    btcprice = load_coin[0]['price_btc']
    current_rank = load_coin[0]['rank']
    price_usd = load_coin[0]['price_usd']
    daily_vol = load_coin[0]['24h_volume_usd']
    market_cap = load_coin[0]['market_cap_usd']
    available_supply = load_coin[0]['available_supply']
    total_supply = load_coin[0]['total_supply']
    max_supply = load_coin[0]['max_supply']
    change_1h = load_coin[0]['percent_change_1h']
    change_24h = load_coin[0]['percent_change_24h']
    change_7d = load_coin[0]['percent_change_7d']

    return render(
        request,
        'predictions/prediction.html',
        {'prediction': prediction, 'target': target,
         'btcprice': btcprice,
         'current_rank': current_rank,
         'price_usd': price_usd,
         'daily_vol': daily_vol,
         'market_cap': market_cap,
         'available_supply': available_supply,
         'total_supply': total_supply,
         'max_supply': max_supply,
         'change_1h': change_1h,
         'change_24h': change_24h,
         'change_7d': change_7d,
         })


def top_predictions(request):
    all_predictions = Prediction.objects.order_by('-votes')
    return render(
        request,
        'predictions/index.html',
        {'all_predictions': all_predictions},
        )


def add_prediction(request):
    if request.method == 'POST':
        prediction_form = CreatePrediction(request.POST)
        if prediction_form.is_valid():
            csrf_token = django.middleware.csrf.get_token(request)
            prediction_title = form.cleaned_data['title']
            prediction_coin_name = form.cleaned_data['coin_name']
            prediction_prediction_type = form.cleaned_data['prediction_type']
            prediction_description = form.cleaned_data['description']
            prediction_entry = form.cleaned_data['entry']
            prediction_stop_loss = form.cleaned_data['stop_loss']
            # prediction_target = form.cleaned_data['target']
            # prediction_target2 = form.cleaned_data['target2']
            # prediction_target3 = form.cleaned_data['target3']
            prediction_user = request.user
            new_prediction = Prediction(
                title=prediction_title,
                coin_name=prediction_coin_name,
                prediction_prediction_type=prediction_type,
                description=prediction_description,
                entry=prediction_entry,
                stop_loss=prediction_stop_loss,
                # prediction_target=prediction_target,
                # prediction_target=prediction_target2,
                # prediction_target=prediction_target3,
                )
            new_prediction.save()
            return render(request, 'predictions/add_prediction.html', {})
    else:
        prediction_form = CreatePrediction()
    return render(request, 'predictions/add_prediction.html',
                  {'prediction_form': prediction_form})


# def vote(request, slug):
#     Prediction.objects.filter(id__in=statements).update(votes=F('votes') + 1)
#     prediction = get_object_or_404(Prediction, coin_name=slug)
#     prediction.votes += 1
#     prediction.save()
#     return HttpResponseRedirect('predictions:prediction')

predictions/templates/predictions/add_prediction.html
{% extends "predictions/header.html" %}
{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'prediction/css/bootstrap.css' %}" />
<form method="post" action="">
    {% csrf_token %}

<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="col">
        
    </div>
    <div class="col-md-4 offset-md-4">
    </div>

        <div class="field">
            <label for="title">Title:</label>
                {{ prediction_form.title}}
        </div>
        <div class="field">
            <label for="description">Description:</label>
            {{ prediction_form.description }}
        </div>
        <div class="field">
            <label for="coin_name">Coin:</label>
            {{ prediction_form.coin_name }}
        </div>
        <div class="field">
            <label for="prediction_type">Type:</label>
            {{ prediction_form.prediction_type }}
        </div>
        <div class="field">
            <label for="entry">Entry:</label>
            {{ prediction_form.entry }}
        </div>
        <div class="field">
            <label for="stop_loss">Stop loss:</label>
            {{ prediction_form.stop_loss }}
        </div>

    <input type="submit" value="Create">
</form>
{% endblock %}

predictions/templates/predictions/header.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'prediction/css/bootstrap.css' %}"/>

    <title>Crypto predictions</title>

      <div class="container">
        <div class="row">
          <div class="col-md-4">BTC price: 3452 $ ETH price: $</div>
          <div class="col-md-4 offset-md-4" align="right">
            <a href="{% url 'login' %}">Login</a>
            <a href="{% url 'logout' %}">Log Out</a>
        </div>
        </div>
        <div class="row">
          <div class="col">
            <a href="{% url 'predictions:index' %}"><img src="{% static 'prediction/images/top_splash.png' %}" class="img-fluid" alt="Crypto-predictions"></a>
          </div>                 
        </div>
        <div class="row">
          <div class="col">
            <nav class="nav nav-pills nav-justified">
                <a class="cd..nav-item nav-link active" href="{% url 'predictions:add_prediction' %}">Add Prediction</a>
                <a class="nav-item nav-link" href="{% url 'predictions:index' %}">Newest</a>
                <a class="nav-item nav-link" href="{% url 'predictions:top_predictions' %}">Top</a>
                <a class="nav-item nav-link" href="#">Contact</a>
                <a class="nav-item nav-link" href="#">Indicators</a>
                <a class="nav-item nav-link" href="#">Hall of Fame</a>
                <a class="nav-item nav-link" href="#">Following</a>
            </nav>
          </div>                 
        </div>
      </div>
      
  </head>

  <body>
  <div class="container">
    <div class="row">
      <div class="col-12">
      {% block content %}
      {% endblock %}
      </div>
    </div>
  </div>



  </body>

</html>

predictions/templates/predictions/index.html
{% extends "predictions/header.html" %}
{% load static %}
{% block content %}

    {% if all_predictions %}
      <div class="container">
        <div class="row">
          <div class="col-12">
          <p></p>
          </div>
        </div>

        {% for p in all_predictions %}
          {% if not forloop.counter|divisibleby:2 %}
              <div class="row">
                <div class="col-6">  
                  <a href ="{% url 'predictions:prediction' p.coin_name %}"><h5>{{ p.title }}</a>
                  {% if p.prediction_type == 'L' %}
                    <img src="{% static 'prediction/icons/long.png' %}" class="img-fluid" alt="Long">
                  {% elif p.prediction_type == 'S' %}
                    <img src="{% static 'prediction/icons/short.png' %}" class="img-fluid" alt="Short">
                  {% endif %}   
                  {% if forloop.counter == 1 %}
                    <img src="{% static 'prediction/icons/crown.png' %}" class="img-fluid" alt="The Winner">
                  {% endif %}
                </h5>
                <div class="row">
                  <div class="col">
                    <p>Published: {{ p.pub_date }}</p>
                  </div>
                  <div class="col">
                    <p align=right>Votes: {{ p.votes }}</p>
                  </div>
                </div>
                  <p>{{ p.description }}</p>
                  <p>Entry: {{ p.entry }}</p>
                  {% for t in p.target_set.all  %}
                    <p>Target {{ forloop.counter }}: {{ t }}</p>
                  {% endfor %}                        
                  <p>Stoploss: {{ p.stop_loss }}</p>
                </div>
          {% elif forloop.counter|divisibleby:2 %}
                <div class="col-6">  
                  <a href ="{% url 'predictions:prediction' p.coin_name %}"><h5>{{ p.title }}</a>
                  {% if p.prediction_type == 'L' %}
                    <img src="{% static 'prediction/icons/long.png' %}" class="img-fluid" alt="Long">
                  {% elif p.prediction_type == 'S' %}
                    <img src="{% static 'prediction/icons/short.png' %}" class="img-fluid" alt="Short">
                  {% endif %}  
                </h5>
                  <div class="row">
                  <div class="col">
                    <p>Published: {{ p.pub_date }}</p>
                  </div>
                  <div class="col">
                    <p align=right>Votes: {{ p.votes }}</p>
                  </div>
                </div>
                  <p>{{ p.description }}</p>
                  <p>Entry: {{ p.entry }}</p>
                  {% for t in p.target_set.all  %}
                    <p>Target {{ forloop.counter }}: {{ t }}</p>
                  {% endfor %}  
                  <p style="display: inline">Stoploss: {{ p.stop_loss }}</p>
                </div>
              </div>
          {% endif %}      
        {% endfor %}
      </div>
        
    {% else %}
        No predictions available.
    {% endif %}

{% endblock %}

predictions/templates/predictions/prediction.html
{% include "predictions/header.html" %}
{% load static %}

<div class="container">
    <div class="row">
        <div class="col">
        <br>
        </div>
    </div>
    <div class="row">
        <div class="col"> 
            <h5>{{ prediction.title }} </h5>
            <p>Published: {{ prediction.pub_date }}</p>
            <p>{{ prediction.description }}</p>   
            <p>BTC price when published: {{ prediction.current_price }}</p>
            <p>Current price: {{ btcprice }}</p>
            {% for t in target %}
                <p>Target {{ forloop.counter }}: {{ t }}</p>
            {% endfor %}
            <p>Get back to all <a href="{% url 'predictions:index' %}">predictions.</a></p>
        </div>
        <div class="col">
            <p>{{ btcprice }}</p>
            <p>{{ current_rank }}</p>
            <p>{{ price_usd }}</p>
            <p>{{ daily_vol }}</p>
            <p>{{ market_cap }}</p>
            <p>{{ available_supply }}</p>
            <p>{{ total_supply }}</p>
            <p>{{ max_supply }}</p>
            <p>{{ change_1h }}</p>
            <p>{{ change_24h }}</p>
            <p>{{ change_7d }}</p>
        </div>
            

             
        </div>
    </div>
</div>