crypto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/predictions/')),
    path('admin/', admin.site.urls),
    path('market/', include('market.urls')),
    path('predictions/', include('predictions.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

market/urls.py
from django.urls import path
from .models import Coin
from . import views

app_name = 'market'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('coin/<slug:slug>/btcprice/', views.btcprice, name='btcprice'),
    path('coin/<slug:slug>/', views.DetailView.as_view(), name='coin'),
]

market/models.py
from django.db import models
from django.utils import timezone


class Coin(models.Model):
    COIN_TYPE = (
        ('PRIV', 'Privacy'),
        ('NETW', 'Network'),
        ('GAME', 'Gaming'),
        ('PLAT', 'Platform'),
        ('PAYM', 'Payment'),
    )
    coin_name = models.SlugField()
    coinname_long = models.SlugField()
    priceBTC = models.FloatField(max_length=10)
    priceUSD = models.FloatField(max_length=10)
    priceETH = models.FloatField(max_length=10)
    coin_type = models.CharField(max_length=50, choices=COIN_TYPE)
    web_site = models.CharField(max_length=100,  blank=True)
    coin_twitter = models.CharField(max_length=100,  blank=True)
    coin_reddit = models.CharField(max_length=100,  blank=True)
    coin_source = models.CharField(max_length=100, blank=True)
    coin_explorer = models.CharField(max_length=200, blank=True)
    coin_telegram = models.CharField(max_length=100, blank=True)
    coin_discord = models.CharField(max_length=100, blank=True)
    coin_tot_supply = models.IntegerField()
    coin_circ_supply = models.IntegerField()
    coin_market_cap = models.IntegerField()
    coin_daily_volume = models.IntegerField()

    def __str__(self):
        return self.coinname_long

market/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
import requests
import bs4

from .models import Coin


class IndexView(generic.ListView):
    template_name = 'market/index.html'
    context_object_name = 'all_coins'

    def get_queryset(self):
        return Coin.objects.order_by('coinname_long')


class DetailView(generic.DetailView):
    model = Coin
    template_name = 'market/coin.html'
    slug_field = 'coinname_long'
    context_object_name = 'coin'


def btcprice(request, slug):
    c = get_object_or_404(Coin, coinname_long=slug)
    coin_url = 'https://coinmarketcap.com/currencies/%s' % (c.coinname_long.lower())
    get_coin = requests.get(coin_url)
    coin_site = bs4.BeautifulSoup(get_coin.text)
    selector = (coin_site.select('#quote_price > span.text-large2'))
    btcprice = selector[0].getText()
    return render(request, 'market/includes/btcprice.html', {'btcprice': btcprice})

market/templates/market/coin.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'market/css/bootstrap.css' %}" />
{% block content %}
    <h1>{{ coin.coinname_long }} </h1>
    {% include 'market/includes/btcprice.html' %}
{% endblock %}

market/templates/market/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'market/css/bootstrap.css' %}"/>

    <title>Avesomo4000's calls</title>
  </head>
    <body>

        <table class="table table-striped table-dark">
            <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Coin</th>
                  <th scope="col">BTC Price</th>
                  <th scope="col">Volume 24h</th>
                </tr>
            </thead>
            {% for c in all_coins %}
                <tbody>
                    <tr>
                      <th scope="row">{{ forloop.counter }}</th>
                      <td><a href ="{% url 'market:coin' c.coinname_long %}">
                        {{ c.coinname_long }}</a></td>
                      <td>
                        {% include 'market/includes/btcprice.html' %}
                      </td>
                      <td>{{ c.coin_daily_volume }}</td>
                    </tr>
                </tbody>
            {% endfor %}
        </table>

    </body>
</html>